management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8888
spring:
    application:
        name: cloudproduct
    cloud:
        nacos:
            discovery:
                server-addr: ${spring.cloud.nacos.server-addr}
            server-addr: localhost:8848
        sentinel:
            enabled: true
            transport:
                dashboard: localhost:8080
                port: 8719